bot:
  token: ${BOT_TOKEN}
  name: "Gretel 2.0"

spring:
  data:
    mongodb:
      authentication-database: admin
      username: user
      password: pass
      database: gretel
      port: 27017
      host: localhost

encryption:
  secretKey: ${SECRET_KEY}

management:
  endpoints:
    web:
     exposure:
       include: "*"
  endpoint:
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      enabled: true

